### ISSUE TITLE
Todo before release

### ISSUE THREAD

**Issue by TehNut** [TehNut-Mods/Buttons#1]
- [ ] Utility buttons should be able to be set to different permission schemes
  - i.e. Somebody wants to use a Magnet button in survival or while not OP'ed
- [ ] A custom Config GUI needs to be made in order to support JSON based configs and to allow a cleaner layout
  - Will include a shortcut to open the GUI _somewhere_
- [ ] Inventory buttons should have a front-end for naming them
  - Will probably stick them into the custom config GUI

There's probably more that I'll add later on
